name: async_zip
description: Asynchronous reading and writing of Zip files.
version: 0.0.1
homepage: http://perron2.ch

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ch.perron2.async_zip
        pluginClass: AsyncZipPlugin
      ios:
        pluginClass: AsyncZipPlugin
